version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: webmart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/opt/homebrew/var/postgresql@14
    ports:
      - "5432:5432"

volumes:
  db-data:
