GET http://localhost:8080/v1/health
Content-Type: application/json

{}
###

POST http://localhost:8080/v1/products
Content-Type: application/json

{
  "user_id": "e41e9bc1-c21d-4673-9f43-e9c5d59baa4d",
  "title": "First Product",
  "description": "check this shit out",
  "rating": 3,
  "price": 20,
  "stock": 5
}
###

POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "name": "a dude",
  "username": "a dude with a username",
  "email": "dude@mail.com",
  "password": "dudepass"
}

###
GET http://localhost:8080/v1/products/6d5895c8-8f04-421a-883a-a53aa2648817
Content-Type: application/json

###
DELETE http://localhost:8080/v1/products/6d5895c8-8f04-421a-883a-a53aa2648817
Content-Type: application/json
