### health check
GET http://localhost:8080/v1/health
Content-Type: application/json

{}

### create product
POST http://localhost:8080/v1/products
Content-Type: application/json

{
  "user_id": "335ba3b3-06ec-4e36-a66e-b333d5e79504",
  "title": "First Product",
  "description": "check this shit out",
  "rating": 3,
  "price": 20,
  "stock": 5
}

### create user
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "name": "a dude",
  "username": "a dude with a username1",
  "email": "dude1@mail.com",
  "password": "dudepass"
}

### get product
GET http://localhost:8080/v1/products/5f3024a2-968f-4553-98f0-c45c348ad04d
Content-Type: application/json

### update product
PATCH http://localhost:8080/v1/products/4e0455c1-0237-4645-9015-382b8b710f75
Content-Type: application/json

{
  "title": "newest title",
  "description": "a whole new description 2",
  "price": 50000,
  "stock": 69
}

### delete product
DELETE http://localhost:8080/v1/products/4e0455c1-0237-4645-9015-382b8b710f75
Content-Type: application/json

### get user
GET http://localhost:8080/v1/users/335ba3b3-06ec-4e36-a66e-b333d5e79504